// <auto-generated />
using System;
using Camera_Shop.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Camera_Shop.Migrations
{
    [DbContext(typeof(CameraContext))]
    [Migration("20200527174604_idk")]
    partial class idk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Camera_Shop.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpecificationsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationsId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Camera_Shop.Models.CameraSpecifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BaseISO")
                        .HasColumnType("integer");

                    b.Property<int>("MaxISO")
                        .HasColumnType("integer");

                    b.Property<decimal>("Megapixels")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CameraSpecifications");
                });

            modelBuilder.Entity("Camera_Shop.Models.Camera", b =>
                {
                    b.HasOne("Camera_Shop.Models.CameraSpecifications", "Specifications")
                        .WithMany()
                        .HasForeignKey("SpecificationsId");
                });
#pragma warning restore 612, 618
        }
    }
}
