// <auto-generated />
using System;
using Camera_Shop.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Camera_Shop.Migrations
{
    [DbContext(typeof(CameraContext))]
    partial class CameraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Camera_Shop.Models.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("SpecificationsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationsId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Camera_Shop.Models.CameraSpecifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BaseISO")
                        .HasColumnType("integer");

                    b.Property<string>("BatteryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ContinuesFPS")
                        .HasColumnType("numeric");

                    b.Property<int>("ExtendedIso")
                        .HasColumnType("integer");

                    b.Property<int>("FastestShutterSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("MaxISO")
                        .HasColumnType("integer");

                    b.Property<int>("MegapixelCountX")
                        .HasColumnType("integer");

                    b.Property<int>("MegapixelCountY")
                        .HasColumnType("integer");

                    b.Property<int>("Megapixels")
                        .HasColumnType("integer");

                    b.Property<string>("Mount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("RatedBatteryLife")
                        .HasColumnType("interval");

                    b.Property<string>("SensorSize")
                        .HasColumnType("text");

                    b.Property<string>("SensorTechnology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ShutterLag")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SingleFPS")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SizeX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SizeY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SizeZ")
                        .HasColumnType("numeric");

                    b.Property<int>("VideoMaxFps")
                        .HasColumnType("integer");

                    b.Property<string>("VideoQuality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<bool>("Wifi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WifiBand")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("CameraSpecifications");
                });

            modelBuilder.Entity("Camera_Shop.Models.Camera", b =>
                {
                    b.HasOne("Camera_Shop.Models.CameraSpecifications", "Specifications")
                        .WithMany()
                        .HasForeignKey("SpecificationsId");
                });
#pragma warning restore 612, 618
        }
    }
}
